<?php

/**
 * @file
 * Build page for popup_window.
 */

/**
 * Include .inc files.
 */
require_once drupal_get_path('module', 'popup_window') . '/includes/popup_window.custom.inc';

/**
 * Implements hook_menu().
 */
function popup_window_menu() {
  $items = array();
  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'description' => 'Custom module for PopUp Window.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer popup_window configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/custom/popup_window'] = array(
    'title' => 'PopUp Window',
    'description' => 'Custom module for PopUp Window.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('popup_window_config_form'),
    'access arguments' => array('administer popup_window configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/popup_window.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function popup_window_theme($existing, $type, $theme, $path) {
  return array(
    'popup_window' => array(
      'template' => 'popup_window',
      'path' => drupal_get_path('module', 'popup_window') . '/theme/tpl',
      'variables' => array(
        'messages' => NULL,
        'popup_window_height' => NULL,
        'popup_window_width' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function popup_window_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['function'] = 'popup_window_render_template';
}
