<?php

/**
 * @file
 * Build page and form for login ajax.
 */

/**
 * Include login_ajax.form.
 */
module_load_include('inc', 'login_ajax', 'includes/login_ajax.form');

/**
 * Form Alter.
 */
function login_ajax_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#ajax' => array(
        'callback' => 'login_ajax_user_login_submit',
        'wrapper' => 'user-login',
        'effect' => 'fade',
        'speed' => 'fast',
        'method' => 'replace',
      ),
      '#value' => t('Log in'),
    );
  }
  if ($form_id == 'user_login_block') {
    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#ajax' => array(
        'callback' => 'login_ajax_user_login_submit',
        'wrapper' => 'user-login-form',
        'effect' => 'fade',
        'speed' => 'fast',
        'method' => 'replace',
      ),
      '#value' => t('Log in'),
    );
  }
}
