<?php

/**
 * @file
 * Build page for node_views_entity.
 */

/**
 * Include .inc files.
 */
require_once 'includes/node_views_entity.form.inc';

/**
 * Implements hook_entity_info().
 */
function node_views_entity_entity_info() {
  return array(
    'node_views_entity' => array(
      'label' => t('Node Views Entity'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'node_views_entity',
      'entity keys' => array(
        'id' => 'rid',
        'label' => 'nid',
      ),
      'admin ui' => array(
        'path' => 'admin/config/custom/node_views_entity',
      ),
      'access callback' => 'node_views_entity_access',
      'module' => 'node_views_entity',
    ),
  );
}

/**
 * Check access.
 */
function node_views_entity_access($op, $entity, $account = NULL, $entity_type = 'node_views_entity') {
  return user_access('administer site configuration');
}

/**
 * Implements hook_node_view().
 */
function node_views_entity_node_view($node, $view_mode, $langcode) {
  global $user;
  $username = $user->uid;
  if ($username) {
    if (flood_is_allowed('node_views_entity_flood', 1, 60, $username)) {
      $table_name = 'node_views_entity';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('node_views_entity_flood', 60, $username);
    }
  }
  else {
    if (flood_is_allowed('node_views_entity_flood', 1, 60)) {
      $table_name = 'node_views_entity';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('node_views_entity_flood', 60);
    }
  }
}
