<?php

/**
 * @file
 * Build page for node_views_entity.
 */

/**
 * Include .inc files.
 */
require_once 'includes/node_views_entity.form.inc';

/**
 * Implements hook_entity_info().
 */
function node_views_entity_entity_info() {
  return array(
    'node_views_entity' => array(
      'label' => t('Node Views Entity'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'node_views_entity',
      'module' => 'node_views_entity',
      'entity keys' => array(
        'id' => 'rid',
      ),
      'admin ui' => array(
        'path' => 'admin/config/custom/node_views_entity',
      ),
      'access callback' => 'node_views_entity_access',
      'module' => 'node_views_entity',
    ),
  );
}

/**
 * Implements hook_entity_access().
 */
function node_views_entity_access($op, $entity, $account = NULL, $entity_type = 'node_views_entity') {
  return user_access('administer site configuration');
}

/**
 * Implements hook_entity_property_info().
 */
function node_views_entity_entity_property_info() {
  $info = array();
  $properties = &$info['node_views_entity']['properties'];
  $properties['created'] = array(
    'label' => t("Created"),
    'type' => 'text',
    'description' => t("Date and time of viewing this node."),
    'schema field' => 'created',
  );
  return $info;
}

/**
 * Implements hook_node_view().
 */
function node_views_entity_node_view($node, $view_mode, $langcode) {
  global $user;
  $username = $user->uid;
  if ($username) {
    if (flood_is_allowed('node_views_entity_flood', 1, 60, $username)) {
      $table_name = 'node_views_entity';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('node_views_entity_flood', 60, $username);
    }
  }
  else {
    if (flood_is_allowed('node_views_entity_flood', 1, 60)) {
      $table_name = 'node_views_entity';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('node_views_entity_flood', 60);
    }
  }
}

/**
 * Implements hook_entity_property_info_alter().
 */
function node_views_entity_views_data_alter(&$data) {
  $data['node_views_entity']['nid']['relationship']['handler'] = 'views_handler_relationship';
  $data['node_views_entity']['nid']['relationship']['title'] = 'nid';
  $data['node_views_entity']['nid']['relationship']['base'] = 'node';
  $data['node_views_entity']['nid']['relationship']['base field'] = 'nid';
  $data['node_views_entity']['uid']['relationship']['handler'] = 'views_handler_relationship';
  $data['node_views_entity']['uid']['relationship']['title'] = 'uid';
  $data['node_views_entity']['uid']['relationship']['base'] = 'users';
  $data['node_views_entity']['uid']['relationship']['base field'] = 'uid';
}
