<?php

/**
 * @file
 * Build page for keywords.
 */

/**
 * Include .inc files.
 */
require_once 'includes/keywords.rules.inc';
require_once 'includes/keywords.form.inc';

/**
 * Implements hook_menu().
 */
function keywords_menu() {
  $items = array();
  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function keywords_entity_info() {
  return array(
    'keywords' => array(
      'label' => t('Keyword'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'keywords',
      'module' => 'keywords',
      'entity keys' => array(
        'id' => 'kid',
        'label' => 'keyword',
      ),
      'admin ui' => array(
        'path' => 'admin/config/custom/keywords',
      ),
      'access callback' => 'keywords_access',
    ),
  );
}

/**
 * Implements hook_entity_access().
 */
function keywords_access($op, $entity, $account = NULL, $entity_type = 'keywords') {
  return user_access('administer site configuration');
}
