<?php

/**
 * @file
 * Build page for popup_window.
 */

/**
 * Include .inc files.
 */
require_once drupal_get_path('module', 'node_views') . '/model/node_views.db.inc';

/**
 * Implements hook_menu().
 */
function node_views_menu() {
  $items = array();
  $items['admin/config/custom/node_views'] = array(
    'title' => 'Node Views',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'node_views_config_page_view',
    'access arguments' => array('administer node_views configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/node_views.custom.inc',
  );
  $items['admin/config/custom/node_views/%'] = array(
    'title' => 'Node Views',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'node_views_config_page_node_view',
    'page arguments' => array(4),
    'access arguments' => array('administer node_views configuration'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'includes/node_views.custom.inc',
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function node_views_node_view($node, $view_mode, $langcode) {
  global $user;
  if (user_is_anonymous()) {
    $username = 0;
  }
  else {
    $username = $user->name;
  }
  if (flood_is_allowed('note_views_flood', 1, 60)) {
    $nid = db_insert('node_views')
      ->fields(array(
        'nodeid' => $node->nid,
        'title' => $node->title,
        'username' => $username,
        'created' => date("Y-m-d H:i:s", time()),
      ))
      ->execute();
    flood_register_event('note_views_flood', 60);
  }
}
