<?php

/**
 * @file
 * Build page for popup_window.
 */

/**
 * Include .inc files.
 */
require_once drupal_get_path('module', 'node_views') . '/model/node_views.db.inc';

/**
 * Implements hook_menu().
 */
function node_views_menu() {
  $items = array();
  $items['admin/config/custom'] = array(
    'title' => 'Custom',
    'position' => 'right',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/custom/node_views'] = array(
    'title' => 'Node Views',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'node_views_config_page_view',
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/node_views.common.inc',
  );
  $items['admin/config/custom/node_views/%'] = array(
    'title' => 'Node Views',
    'description' => 'Custom module for Node Views.',
    'page callback' => 'node_views_config_page_node_view',
    'page arguments' => array(4),
    'access arguments' => array('administer'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'includes/node_views.common.inc',
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function node_views_node_view($node, $view_mode, $langcode) {
  global $user;
  $username = $user->uid;
  if ($username) {
    if (flood_is_allowed('note_views_flood', 1, 60, $username)) {
      $table_name = 'node_views';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('note_views_flood', 60, $username);
    }
  }
  else {
    if (flood_is_allowed('note_views_flood', 1, 60)) {
      $table_name = 'node_views';
      $row = new stdClass();
      $row->nid = $node->nid;
      $row->uid = $username;
      $row->created = date("Y-m-d H:i:s", time());
      drupal_write_record($table_name, $row);
      flood_register_event('note_views_flood', 60);
    }
  }
}
