<?php

/**
 * @file
 * Build page and form for calculator.
 */

/**
 * Imlenents hook_menu().
 */
function calculator_menu() {
  $items = array();
  $items['calculator-page'] = array(
    'title' => 'Calculator',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculator_page_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Build calculator form.
 */
function calculator_page_form($form, $form_state) {
  $form = array();
  $form['number1'] = array(
    '#type' => 'textfield',
    '#title' => t('Number 1'),
    '#size' => 20,
  );
  $form['number2'] = array(
    '#type' => 'textfield',
    '#title' => t('Number 2'),
    '#size' => 20,
  );
  $form['operator'] = array(
    '#type' => 'select',
    '#title' => t('Operator'),
    '#options' => array('+', '-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Calculate'),
  );
  return $form;
}
