<?php

/**
 * @file
 * Build page and form for calculator.
 */

/**
 * Imlenents hook_menu().
 */
function calculator_menu() {
  $items = array();
  $items['calculator-page'] = array(
    'title' => 'Calculator',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculator_page_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Build calculator form.
 */
function calculator_page_form($form, $form_state) {
  $form = array();
  $form['number1'] = array(
    '#type' => 'textfield',
    '#title' => t('Number 1'),
    '#size' => 20,
  );
  $form['number2'] = array(
    '#type' => 'textfield',
    '#title' => t('Number 2'),
    '#size' => 20,
  );
  $form['operator'] = array(
    '#type' => 'select',
    '#title' => t('Operator'),
    '#options' => array('+', '-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Calculate'),
  );

  return $form;
}

/**
 * Validate finction for calculator_page_form.
 */
function calculator_page_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['number1'])) {
    form_set_error('number1', t('Value is field "Number 1" is wrong'));
  }

  if (!is_numeric($form_state['values']['number2'])) {
    form_set_error('number2', t('Value is field "Number 2" is wrong'));
  }
}

/**
 * Submit function for calculator_page_form.
 */
function calculator_page_form_submit($form, &$form_state) {
  $num1 = $form_state['values']['number1'];
  $num2 = $form_state['values']['number2'];

  switch ($form_state['values']['operator']) {
    case 0:
      $result = $num1 + $num2;
      break;

    default:
      $result = $num1 - $num2;
      break;
  }

  drupal_set_message(t('Result is @num', array('@num' => $result)));
}
